### PR TITLE
Generate table names from address

### LINKED ISSUE #772: as a user, I want tables to have human-readable names
Where can we find a list of fancy city names? Tree names? Other ideas?

Rough idea:
1. each table gets a name from the list based on tableId, ex. "Monaco"
2. do not reuse names, as there shouldn't be more than, say, 100+ tables ever.
2. However, if table-list is already used, append with 00#? ex "Monaco-001"

### PR DESCRIPTION
**Pull request by sunify**
Resolves #772 

I generate a table name from lists of colors and fuits+veggetables. Sandbox tables:

image

What do you think guys?

### CODE REVIEW

**Comment by troggy** [comment]
haha.. like it! Although veggie names are not quite matching our imperial-star-wars-alike style (website and whitepaper)

**Comment by johannbarbie** [comment]
Good idea to combine 2 words. How about if i'm on the table already, and want to tell my friend to join, can i see the name somewhere?

**Comment by sunify** [comment]
@troggy yeah, you're right. Maybe we should pick some nouns from Battlestrar Galactica, StarGate and such other shows

@johannbarbie now you can see it only in empty chatbox as a placeholder. I'll try to put the name somewhere else

**Comment by VonIobro** [comment]
Looks good. I'd defer to some marketing types for the list sets. For the table, I think it would be nice if the table ID was in it's own column since it is always the same length.

**Comment by m-kroener** [comment]
Nice, I like it! When we put the name somewhere else on the table so players can invite others by telling the table name, that would be great. Maybe even with a share button (Twitter/Facebook) attached to the name, so people can look for opponents in public? 

Personally I prefer the star wars theme. I thought maybe using Blockchain/Crypto related names but I couldn't come up with some, so I guess that's not working.

**Comment by sunify** [comment]
Looks like everyone likes space-related themes :-)

What about planets? Solar system (8 + some smaller bodies) + BSG (12) + some star wars universe, mass effect etc

**Comment by m-kroener** [comment]
Cool!

**Comment by sunify** [comment]
Updates

image

image

image

**Comment by troggy** [comment]
good stuff!

btw, pokerstars use Space theme for table naming as well: http://www.flopturnriver.com/reviews/screenshots/PokerStars-Lobby.jpg
everyone loves Space :)

**Pull request merged**
